# Base configs
# baseurl: "https://photography.rampatra.com"
baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
# google_analytics: "UA-46465113-2"

# UI configs
title: "Unit 810"
subtitle: "Live in the heart of downtown Phoenix in one of its most iconic historic buildings — Orpheum Lofts"
author: "Unit 810 LLC"
header:
 title: "Unit 810"
 subtitle: "Historic Loft Living in Downtown Phoenix"
